2021-07-01 11:43:04.773106: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-07-01 11:43:04.807686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00GiB/s
2021-07-01 11:43:04.808279: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-07-01 11:43:04.812668: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-07-01 11:43:04.815824: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-07-01 11:43:04.816852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-07-01 11:43:04.820204: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-07-01 11:43:04.821793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-07-01 11:43:04.827427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-07-01 11:43:04.828202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-07-01 11:43:04.828542: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-07-01 11:43:04.836268: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3600000000 Hz
2021-07-01 11:43:04.836611: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f027c000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-07-01 11:43:04.836633: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-07-01 11:43:04.903783: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d81fb09920 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-07-01 11:43:04.903829: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro P5000, Compute Capability 6.1
2021-07-01 11:43:04.904615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 269.00GiB/s
2021-07-01 11:43:04.904697: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-07-01 11:43:04.904726: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-07-01 11:43:04.904749: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2021-07-01 11:43:04.904772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2021-07-01 11:43:04.904794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2021-07-01 11:43:04.904817: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2021-07-01 11:43:04.904840: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-07-01 11:43:04.905848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2021-07-01 11:43:04.905918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-07-01 11:43:04.906602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-01 11:43:04.906634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2021-07-01 11:43:04.906647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2021-07-01 11:43:04.907718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 345 MB memory) -> physical GPU (device: 0, name: Quadro P5000, pci bus id: 0000:65:00.0, compute capability: 6.1)
2021-07-01 11:43:10.190741: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2021-07-01 11:43:10.327887: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-07-01 11:43:10.617762: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-07-01 11:43:10.621969: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-07-01 11:43:10.624710: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-07-01 11:43:10.626401: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
NUM_ITER 70
BATCH_SIZE 50
NUM_BATCH 100
NUM_SNPS 36
L 50000
NUM_CLASSES 2
NUM_CHANNELS 2
NUM_ITER 300
BATCH_SIZE 50
NUM_BATCH 100
NUM_SNPS 36
L 50000
NUM_CLASSES 2
NUM_CHANNELS 2
{'model': 'ooa2', 'params': 'N_anc,N1,N2,N3,T1,T2,mig', 'data_h5': '/bigdata/smathieson/pg-gan/1000g/HDF5/YRI_CEU.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.h5', 'bed': '/bigdata/smathieson/pg-gan/1000g/HDF5/20120824_strict_mask.bed', 'reco_folder': '/bigdata/smathieson/pg-gan/1000g/genetic_map/', 'grid': None, 'toy': None, 'seed': 1833}
N_anc,N1,N2,N3,T1,T2,mig
[<util.Parameter object at 0x7f0432e99b10>, <util.Parameter object at 0x7f0432e99d50>, <util.Parameter object at 0x7f04327f8fd0>, <util.Parameter object at 0x7f04a6e65f50>, <util.Parameter object at 0x7f04327a7650>, <util.Parameter object at 0x7f04327a7550>, <util.Parameter object at 0x7f04327a7490>]
['N_anc', 'N1', 'N2', 'N3', 'T1', 'T2', 'mig']
NAME	VALUE	MIN	MAX
N_anc	15000	1000	25000
NAME	VALUE	MIN	MAX
mig	0.05	-0.2	0.2
NAME	VALUE	MIN	MAX
N1	9000	1000	30000
NAME	VALUE	MIN	MAX
N2	5000	1000	30000
NAME	VALUE	MIN	MAX
N3	12000	1000	30000
NAME	VALUE	MIN	MAX
T1	2000	1500	5000
NAME	VALUE	MIN	MAX
T2	350	100	1500
['calldata', 'variants']
['GT'] ['CHROM', 'POS']
raw (20884132, 98, 2)
after haps (20884132, 196)
Parsing HapMap recombination rates...
parameters <class 'list'> [<util.Parameter object at 0x7f0432e99b10>, <util.Parameter object at 0x7f0432e99d50>, <util.Parameter object at 0x7f04327f8fd0>, <util.Parameter object at 0x7f04a6e65f50>, <util.Parameter object at 0x7f04327a7650>, <util.Parameter object at 0x7f04327a7550>, <util.Parameter object at 0x7f04327a7490>]
Model: "two_pop_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 98, 32, 32)        352       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 98, 12, 64)        10304     
_________________________________________________________________
max_pooling2d (MaxPooling2D) multiple                  0         
_________________________________________________________________
flatten (Flatten)            (None, 384)               0         
_________________________________________________________________
concatenate (Concatenate)    (None, 768)               0         
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               98432     
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 516       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 5         
=================================================================
Total params: 126,121
Trainable params: 126,121
Non-trainable params: 0
_________________________________________________________________
pretraining starts
at iteration  1
Traceback (most recent call last):
  File "pg_gan.py", line 435, in <module>
    main()
  File "pg_gan.py", line 65, in main
    iterator, VAE_model, parameters, opts.seed, toy=opts.toy)
  File "pg_gan.py", line 177, in simulated_annealing
    s_current = pg_gan.disc_pretraining(800, BATCH_SIZE)
  File "pg_gan.py", line 329, in disc_pretraining
    self.VAE_model.run_training()
  File "/homes/tdo/pg-gan2/VAE_train.py", line 45, in run_training
    self.training_sa(VAE_NUM_BATCH, VAE_BATCH_SIZE) 
  File "/homes/tdo/pg-gan2/VAE_train.py", line 37, in training_sa
    loss = train_step(self.model, real_regions, optimizer)
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/packages/cs/python3.7.7/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node encoder_two_pop/conv2d_2/Conv2D (defined at /homes/tdo/pg-gan2/VAE.py:95) ]] [Op:__inference_train_step_1853]

Errors may have originated from an input operation.
Input Source operations connected to node encoder_two_pop/conv2d_2/Conv2D:
 encoder_two_pop/strided_slice (defined at /homes/tdo/pg-gan2/VAE.py:91)

Function call stack:
train_step

